version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: WarehouseWebsite.Web/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgres
      - azurite
      - smtp
    networks:
      - net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123$
      POSTGRES_DB: WarehouseDb
    ports:
      - "5432:5432"
    networks:
      - net

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log"
    networks:
      - net
  
  smtp: 
    image: mailhog/mailhog 
    container_name: mailhog
    ports: 
      - "8025:8025" # MailHog Web UI
      - "1025:1025" # SMTP
    networks:
      - net

networks:
  net:
